COPY Diagnostic FROM './dataset/node_diagnostics.csv';
COPY Disease FROM './dataset/node_diseases.csv';
COPY MedicalSpecialty FROM './dataset/node_medical_specialties.csv';
COPY Symptom FROM './dataset/node_symptoms.csv';
COPY Treatment FROM './dataset/node_treatments.csv';
COPY DIAGNOSED_BY FROM './dataset/rel_disease_diagnostic.csv';
COPY MANAGED_BY FROM './dataset/rel_disease_specialty.csv';
COPY HAS_SYMPTOM FROM './dataset/rel_disease_symptom.csv';
COPY TREATED_BY FROM './dataset/rel_disease_treatment.csv';